# Authentication Routes

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "atilolaemmanuel22@gmail.com",
    "password": "Test1234"
}
###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "atilolaemmanuel2023@gmail.com",
    "password": "Test1234"
}
###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "atilolaemmanuel23@gmail.com",
    "password": "Test1234"
}


###
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "fullname": "Samuel",
    "email": "atilolaemmanuel22@gmail.com",
    "password": "Test1234"
}

###
GET http://localhost:3000/api/auth/logout


###
GET http://localhost:3000/api/auth/check-auth
###
GET http://localhost:3000/api/auth/user-info/69b6ab1e0652066a480f9916

###
PUT http://localhost:3000/api/auth/update-profile
Content-Type: application/json

{
    "fullname": "Atilola Emmanuel Oluwatoba"

}



### Message Routes
POST   http://localhost:3000/api/message/send/69b58d2924bf49d97d8c4999
Content-Type: application/json

{
    "text": "Hey dear"
}
###
POST   http://localhost:3000/api/message/send/69b6ab1e0652066a480f9916
Content-Type: application/json

{
    "text": "What are you doing?"
}



###
GET http://localhost:3000/api/message/69b58d2924bf49d97d8c4999

###
GET http://localhost:3000/api/message/chats


###
DELETE  http://localhost:3000/api/message/delete/69b6df246382e5506e9271f6