POST http://localhost:3000/api/auth/login

###
POST http://localhost:3000/api/auth/register


###
GET http://localhost:3000/api/auth/logout



### Message Routes
POST http://localhost:3000/api/message/send


###
GET http://localhost:3000/api/message/receive