POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "atilolaemmanuel22@gmail.com",
    "password": "Test1234"
}

###
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "fullname": "Atilola Emmanuel",
    "email": "atilolaemmanuel22@gmail.com",
    "password": "Test1234"
}

###
GET http://localhost:3000/api/auth/logout


###
GET http://localhost:3000/api/auth/check-auth


###
PUT http://localhost:3000/api/auth/update-profile
Content-Type: application/json

{
    "fullname": "Atilola Emmanuel Oluwatoba"

}


### Message Routes
POST http://localhost:3000/api/message/send


###
GET http://localhost:3000/api/message/receive